name: Build Windows Executable

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install pipreqs
        run: |
          pip install pipreqs 

      - name: Make dist folder
        run: mkdir dist/geoff

      - name: Make requirements.txt file
        run: pipreqs . --encoding utf-8 --ignore .\unittests\,.\separator_settings\,.\binaries\,.\assets\,.\.venv\ --force

      - name: Build app
        run: flet build windows --module-name ${{ github.workspace }}/main.py  --output dist/geoff --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: geoff
          path: dist
